// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSXAfMLyB-YCSFib4s1IaA-oexuoxdpM',
    appId: '1:289738527788:web:eaee651f40845859af2d89',
    messagingSenderId: '289738527788',
    projectId: 'learning-app-flutter-13319',
    authDomain: 'learning-app-flutter-13319.firebaseapp.com',
    storageBucket: 'learning-app-flutter-13319.firebasestorage.app',
    measurementId: 'G-X78XY9KSHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcH73zuT-H1JZLRItrUF8NuZZyggia_KA',
    appId: '1:289738527788:android:2bae5c63a34c16a8af2d89',
    messagingSenderId: '289738527788',
    projectId: 'learning-app-flutter-13319',
    storageBucket: 'learning-app-flutter-13319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBL8LjSGjeC7M-RoT412IZrS92FZle760',
    appId: '1:289738527788:ios:08214e84dee107b5af2d89',
    messagingSenderId: '289738527788',
    projectId: 'learning-app-flutter-13319',
    storageBucket: 'learning-app-flutter-13319.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBL8LjSGjeC7M-RoT412IZrS92FZle760',
    appId: '1:289738527788:ios:08214e84dee107b5af2d89',
    messagingSenderId: '289738527788',
    projectId: 'learning-app-flutter-13319',
    storageBucket: 'learning-app-flutter-13319.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSXAfMLyB-YCSFib4s1IaA-oexuoxdpM',
    appId: '1:289738527788:web:9fe58020a5813b12af2d89',
    messagingSenderId: '289738527788',
    projectId: 'learning-app-flutter-13319',
    authDomain: 'learning-app-flutter-13319.firebaseapp.com',
    storageBucket: 'learning-app-flutter-13319.firebasestorage.app',
    measurementId: 'G-M8RBJ8QZXK',
  );
}
